version: '3.8'

services:
  # ChromaDB for vector embeddings and intelligent element search (optional)
  chromadb:
    image: chromadb/chroma:latest
    container_name: revit-mcp-chromadb
    ports:
      - "8000:8000"
    volumes:
      - ./chroma-data:/chroma/chroma
    environment:
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.token.TokenAuthServerProvider
      - CHROMA_SERVER_AUTH_CREDENTIALS=${CHROMA_AUTH_TOKEN:-test-token}
      - CHROMA_SERVER_AUTH_TOKEN_TRANSPORT_HEADER=AUTHORIZATION
      - PERSIST_DIRECTORY=/chroma/chroma
      - IS_PERSISTENT=TRUE
    restart: unless-stopped
    networks:
      - revit-mcp-network

  # Redis for caching and rate limiting (optional)
  redis:
    image: redis:7-alpine
    container_name: revit-mcp-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    command: >
      --requirepass ${REDIS_PASSWORD:-revit-mcp-redis-pass}
      --save 60 1
      --save 300 10
      --save 900 100
    restart: unless-stopped
    networks:
      - revit-mcp-network

networks:
  revit-mcp-network:
    driver: bridge

volumes:
  chroma-data:
  redis-data: