name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'
    
    - name: Install dependencies
      run: npm ci
    
    # Skip tests for now - they need fixing
    # - name: Run tests
    #   run: npm test
    
    - name: Build
      run: npm run build
    
    - name: Create Release Archive
      run: |
        tar -czf revit-mcp-${{ github.ref_name }}.tar.gz \
          build/ \
          package.json \
          package-lock.json \
          README.md \
          LICENSE \
          .env.example \
          docker-compose.yml
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: revit-mcp-${{ github.ref_name }}.tar.gz
        generate_release_notes: true
        body: |
          ## 🏗️ Revit MCP Server
          
          TypeScript implementation of MCP server for Autodesk Revit integration.
          
          ## Installation
          
          ### Via npm (recommended):
          ```bash
          npm install revit-mcp@${{ github.ref_name }}
          ```
          
          ### Via release archive:
          1. Download the release archive
          2. Extract: `tar -xzf revit-mcp-${{ github.ref_name }}.tar.gz`
          3. Install dependencies: `npm install --production`
          4. Configure environment variables (see `.env.example`)
          5. Add to Claude Desktop configuration
          
          ## Configuration
          
          Add to your Claude Desktop `claude_desktop_config.json`:
          ```json
          {
            "mcpServers": {
              "revit-mcp": {
                "command": "node",
                "args": ["<path-to-project>/build/index.js"]
              }
            }
          }
          ```
          
          ## What's Changed
          See below for full changelog.
    
    # Docker build removed - no Dockerfile exists after refactoring
    # The TypeScript MCP server doesn't need containerization
    # Optional services (Redis, ChromaDB) have their own docker-compose.yml
    
    - name: Publish to NPM
      if: contains(github.ref, 'beta') == false
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      continue-on-error: true  # Don't fail release if NPM publish fails